name: GitHub Release Action
run-name: ${{ github.actor }} is building a release!
on:
  push:
    branches:
      - main

jobs:
  release: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Create Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: MakerMilling_Project_Angular/src
            tag: v0.0.${{ github.run_number }}
            release_name: v0.0.${{ github.run_number }}
            overwrite: true 

  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
  
      - name: Install dependencies
        run: |
          cd MakerMilling_Project_Angular 
          npm install
  
      - name: Build
        run: |
          cd MakerMilling_Project_Angular 
          npm run build
          
      - name: Zip
        run: |
          cd MakerMilling_Project_Angular/dist
          zip -r dist.zip angular
          pwd
          ls
          
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/MakerMilling_angular/MakerMilling_angular/dist.zip
          tag: v0.0.${{ github.run_number }}
          asset_name: makermilling_dist.zip
          overwrite: true
          prerelease: true
