name: GitHub Release Action
run-name: ${{ github.actor }} is building a release!
on:
  push:
    branches:
      - main

jobs:
  release: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Create Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: MakerMilling_Project_Angular/src
            tag: v.0.0.${{ github.run_number }}
            release_name: v.0.0.${{ github.run_number }}
            overwrite: true 

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: NPM Install
        run: npm install
      - name: NPM Install Angular
        run: npm install -g @angular/cli &gt; /dev/null
      - name: NPM build Angular Production
        run: ng build --prod
